---
- name: Simple Application Deployment
  hosts: my_servers
  become: true
  remote_user: samirwadkar31
  tasks:
    - name: Ensure apt cache is up-to-date
      apt:
        update_cache: yes
    - name: Upgrade all packages to the latest version
      apt:
        upgrade: dist
    - name: Install apache http server
      apt:
        name: apache2
        state: present
        update_cache: yes
    - name: Copy file with owner and permissions
      copy:
        src: /home/samirwadkar31/Ansible_Project/Simple_Application_Deployment/index.html
        dest: /var/www/html
        owner: root
        group: root
        mode: '0644'
